spring:

  application:
    name: translator

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml


integrations:
  yandex:
    api-key: ${YANDEX_API_KEY}
    url: https://translate.api.cloud.yandex.net/translate/v2/translate
    max-requests-per-second: 20
    retry-delay-in-seconds: 1